### EXPERIMENT PARAMETERS
SIMULATION_TIME = 60## in seconds
DISCRETE_TIME_UNIT = 10
DELAY_PER_CYCLE = 2
SUB_EXP_COUNT = SIMULATION_TIME/DISCRETE_TIME_UNIT
BASE_STATION_X = 100
BASE_STATION_Y = 100
PACKET_RECEPTION_RATE = 10 ## in mbps
SIGNAL_PROPAGATION_SPEED = 300000000 ## m/s
PROCESSING_DELAY = 0.1 ## in s

##screen parameters
BACKGROUND_COLOR=(255,255,255)#'white'
LENGTH = 800
BREADTH = 600

### mobile node parameters
MOBILE_NODE_COUNT = 20
MOBILE_NODE_RADIUS = 3
MOBILE_NODE_FILL_COLOR = (0,0,0)#'black'
MOBILE_NODE_OUTLINE_COLOR = (0,0,0)#'black'
MOBILE_NODE_SPEED = 1
RANGE_RADIUS = LENGTH/(MOBILE_NODE_COUNT)

### mobile robot parameters
MOBILE_ROBOT_COUNT = 5
MOBILE_ROBOT_RADIUS = 5
MOBILE_ROBOT_FILL_COLOR = (0,255,0)#'green'
MOBILE_ROBOT_OUTLINE_COLOR = (0,255,0)#'green'
MOBILE_ROBOT_SPEED = MOBILE_NODE_SPEED

## ACO parameters
INITIAL_PHEROMONE = 1
ANTS_PER_ITERATION = 1000
ANTS_NUMBER_STEPS = 10000
PHEROMONE_EVAPORATION_RATE = 0.1
ALPHA = 2

